# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  encoding: utf8
  host: charitys-imac
  database: studiopsyche
  username: studiopsyche
  password: studiopsyche

test:
  adapter: postgresql
  encoding: utf8
  host: charitys-imac
  database: studiopsyche
  username: studiopsyche
  password: studiopsyche

production:
  adapter: postgresql
  encoding: utf8
  host: charitys-imac
  database: studiopsyche
  username: studiopsyche
  password: studiopsyche

